sudo: required
language: generic

services:
  - docker

before_deploy: "echo 'before deploy'"
  - docker build -t ag/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ag/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: 'us-east-1'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-634437713025'
  bucket_path: 'docker'
  on:
    branch: master

after_deploy: "echo 'after deploy'"
